# Generated by Django 4.2.6 on 2023-10-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_cart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
