# Generated by Django 4.2.6 on 2023-10-31 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_alter_product_pdetails_alter_product_pimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeapp', '0004_cart_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_id',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
